[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.package]
edition = "2024"

[workspace.dependencies]
dictate-debug = { path = "crates/dictate-debug" }
dictate-desktop = { path = "crates/dictate-desktop" }
dictate-signal = { path = "crates/dictate-signal" }
dictate-speech = { path = "crates/dictate-speech" }
dictate-ui = { path = "crates/dictate-ui" }
gpui = { git = "https://github.com/zed-industries/zed", rev = "50d001fe0a38a1c326711541cca5204b7f19557f", package = "gpui" }
gpui_platform = { git = "https://github.com/zed-industries/zed", rev = "50d001fe0a38a1c326711541cca5204b7f19557f", package = "gpui_platform", features = ["wayland"] }

anyhow = "1"
bzip2 = "0.6"
clap = { version = "4.5", features = ["derive", "string"] }
cpal = "0.18"
directories = "6"
futures = "0.3"
hound = "3.5"
rtrb = "0.3"
rustfft = "6.4"
rustix = { version = "1", features = ["event", "net"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sherpa-onnx = "1.13"
tar = "0.4"
thiserror = "2"
toml = "1.1"
ureq = "3.3"
wl-clipboard-rs = "0.9"

insta = "1"
strsim = "0.11"

[workspace.lints.clippy]
pedantic = { level = "warn", priority = -1 }

# pedantic
missing_errors_doc = "allow"

# restriction
clone_on_ref_ptr = "warn"
dbg_macro = "warn"
expect_used = "warn"
get_unwrap = "warn"
let_underscore_must_use = "warn"
map_err_ignore = "warn"
mem_forget = "warn"
mod_module_files = "warn"
multiple_unsafe_ops_per_block = "warn"
panic_in_result_fn = "warn"
todo = "warn"
undocumented_unsafe_blocks = "warn"
unimplemented = "warn"
unreachable = "warn"
unused_result_ok = "warn"
unwrap_in_result = "warn"
unwrap_used = "warn"
wildcard_enum_match_arm = "warn"

[profile.dev.package."*"]
opt-level = 2
