#!/bin/sh

project_path=""
pid_file="/tmp/bar-rs.pid"
log_file="/tmp/bar-rs.log"

open() {
    target="release"
    for arg in "$@"; do
        if [ "$arg" == "--debug" ]; then
            target="debug"
            break
        fi
    done

    if [ -f "$pid_file" ] && pid=$(<"$pid_file") && kill -0 "$pid" 2>/dev/null; then
        echo -e "bar-rs is already running with PID $pid,\nrun \`bar-rs kill\` to close it"
        exit 1
    fi

    cmd="$project_path/target/$target/bar-rs"

    if [ ! -f "$cmd" ]; then
        echo -e "$cmd does not exist, make sure to build bar-rs using:\n\t\`cargo build --release\`\nor reinstall this script if you've moved the project directory:\n\t\`bash install.sh\`"
        exit 1
    fi

    RUST_BACKTRACE=full nohup $cmd > $log_file 2>&1 &
    echo $! > $pid_file
}

close() {
    if [ -f "$pid_file" ]; then
        pid=$(<"$pid_file")
        kill -2 $pid
        rm $pid_file
    else
        echo "PID file ($pid_file) does not exist. Exiting."
        exit 1
    fi
}

uninstall() {
    path=$(realpath "$0")
    if [ "$(dirname $path)" == "/usr/local/bin" ]; then
        if [ "$UID" -ne 0 -a "$EUID" -ne 0 ]; then
            sudo rm $path
        else
            rm $path
        fi
    else
        echo This script is not installed to /usr/local/bin, you should remove it manually if desired
        exit 1
    fi
}

# MAIN
case "$1" in
    open)
        open $@
        ;;
    kill)
        close
        ;;
    reopen)
        close
        open $@
        ;;
    uninstall)
        uninstall
        ;;
    *)
        echo "bar-rs: bar-rs [open | kill | reopen | uninstall] [--debug]"
        ;;
esac
