[package]
name = "dictate"
version = "0.1.0"
description = "Voice-to-text transcription for Linux"
authors = ["Josh Thomas <josh@joshthomas.dev>"]
edition.workspace = true

[dependencies]
dictate-debug.workspace = true
dictate-desktop.workspace = true
dictate-signal.workspace = true
dictate-speech.workspace = true
dictate-ui.workspace = true

anyhow.workspace = true
clap.workspace = true
directories.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true

[dev-dependencies]
xkbcommon.workspace = true

[lints]
workspace = true
