name: test

on:
  pull_request:
    branches:
      - main
    paths:
      - .github/workflows/test.yml
      - .rustfmt.toml
      - Cargo.lock
      - Cargo.toml
      - rust-toolchain.toml
      - src/**
      - tests/**
  push:
    branches:
      - main
    paths:
      - .github/workflows/test.yml
      - .rustfmt.toml
      - Cargo.lock
      - Cargo.toml
      - rust-toolchain.toml
      - src/**
      - tests/**

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  test:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends \
            build-essential \
            clang \
            cmake \
            glslc \
            libasound2-dev \
            libfontconfig-dev \
            libglib2.0-dev \
            libssl-dev \
            libstdc++-14-dev \
            libva-dev \
            libvulkan-dev \
            libvulkan1 \
            libwayland-dev \
            libx11-xcb-dev \
            libxkbcommon-dev \
            libxkbcommon-x11-dev \
            libzstd-dev \
            lld \
            llvm \
            pkg-config

      - name: Cache rustup toolchain
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.rustup
          key: ${{ runner.os }}-${{ runner.arch }}-rustup-pinned-${{ hashFiles('rust-toolchain.toml') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-rustup-pinned-

      - name: Cache Cargo dependencies
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
          key: ${{ runner.os }}-${{ runner.arch }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ runner.arch }}-cargo-registry-
            ${{ runner.os }}-cargo-registry-

      - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659

      - name: Test
        run: cargo test
