mod audio_ducking;
mod delivery;
mod focus;
mod global_shortcuts;
mod insertion;

pub use audio_ducking::AudioDucker;
pub use audio_ducking::AudioDuckingError;
pub use audio_ducking::DuckGuard;
pub use delivery::ConfirmedDeliveryTarget;
pub use delivery::DeliveryAttemptFailure;
pub use delivery::DeliveryReport;
pub use delivery::DeliveryTarget;
pub use delivery::deliver;
pub use focus::FocusObservation;
pub use focus::FocusSnapshot;
pub use focus::FocusedWindow;
pub use focus::observe;
pub use focus::snapshot;
pub use global_shortcuts::PushToTalkError;
pub use global_shortcuts::PushToTalkEvent;
pub use global_shortcuts::PushToTalkShortcut;
pub use global_shortcuts::listen_push_to_talk;
pub use insertion::ClipboardOperation;
pub use insertion::ClipboardRestoration;
pub use insertion::ClipboardTransactionFailure;
pub use insertion::CompletedInsertion;
pub use insertion::DirectTypingClipboard;
pub use insertion::UncertainInsertion;
